const { withAppBuildGradle } = require('expo/config-plugins');

/**
 * Sign release builds with OUR key instead of the debug one.
 *
 * WHY THIS EXISTS AT ALL: the Expo/RN template points its `release`
 * signingConfig at `debug.keystore` so that `assembleRelease` works with no
 * setup. That keystore is the well-known Android debug key — same bytes, same
 * `android` password, in every React Native project on earth. Two consequences
 * we actually hit:
 *
 *  1. It cannot anchor an identity. Google Sign-In ties an OAuth client to
 *     `package name + signing SHA-1`, and a fingerprint that everyone else also
 *     has is not proof of anything — anyone could ship an app that signs in as
 *     us.
 *  2. Anything published to a store is stuck with the key it was first signed
 *     with, forever. Discovering this after the first release is not a fixable
 *     mistake.
 *
 * WHY A PLUGIN AND NOT AN EDIT: `android/` is generated by `expo prebuild` and
 * is gitignored, so any change made in it is erased by the next prebuild — in
 * CI, that is every single build.
 *
 * WITHOUT THE ENV VARS THIS IS A NO-OP and the template's debug signing stays.
 * That keeps a plain `npx expo prebuild` working for a contributor who has no
 * keystore, instead of failing on a secret they cannot have.
 */

const CONFIG_NAME = 'driftoraRelease';

/** `\` and `'` are the only characters that can break a single-quoted Groovy literal. */
function groovyString(value) {
  return `'${String(value).replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
}

function injectSigningConfig(contents, env) {
  const config = `
        ${CONFIG_NAME} {
            storeFile file(${groovyString(env.storeFile)})
            storePassword ${groovyString(env.storePassword)}
            keyAlias ${groovyString(env.keyAlias)}
            keyPassword ${groovyString(env.keyPassword)}
            // PKCS#12, not JKS: the key was made with openssl (no Java on the
            // machine that generated it). Java 9+ reads it natively.
            storeType 'PKCS12'
        }`;

  // Add the config inside the existing `signingConfigs { … }` block.
  const anchor = 'signingConfigs {';
  const at = contents.indexOf(anchor);
  if (at === -1) throw new Error('withReleaseSigning: no signingConfigs block in app/build.gradle');
  let out = contents.slice(0, at + anchor.length) + config + contents.slice(at + anchor.length);

  // Point the release buildType at it. The template line is
  // `signingConfig signingConfigs.debug` inside `buildTypes { release { … } }`.
  const releaseAt = out.indexOf('release {', out.indexOf('buildTypes {'));
  if (releaseAt === -1) throw new Error('withReleaseSigning: no release buildType in app/build.gradle');
  const debugLine = 'signingConfig signingConfigs.debug';
  const lineAt = out.indexOf(debugLine, releaseAt);
  if (lineAt === -1) {
    throw new Error('withReleaseSigning: release buildType does not use signingConfigs.debug — template changed');
  }
  out = out.slice(0, lineAt) + `signingConfig signingConfigs.${CONFIG_NAME}` + out.slice(lineAt + debugLine.length);
  return out;
}

const withReleaseSigning = function (config) {
  return withAppBuildGradle(config, (cfg) => {
    const env = {
      storeFile: process.env.ANDROID_KEYSTORE_PATH,
      storePassword: process.env.ANDROID_KEYSTORE_PASSWORD,
      keyAlias: process.env.ANDROID_KEY_ALIAS,
      // The p12 was exported with one password for both, which is what openssl
      // does; a separate key password is still honoured if it is ever set.
      keyPassword: process.env.ANDROID_KEY_PASSWORD || process.env.ANDROID_KEYSTORE_PASSWORD,
    };

    if (!env.storeFile || !env.storePassword || !env.keyAlias) return cfg;

    if (cfg.modResults.language !== 'groovy') {
      throw new Error('withReleaseSigning: expected a Groovy build.gradle (Expo SDK 54 template).');
    }
    if (cfg.modResults.contents.includes(CONFIG_NAME)) return cfg;

    cfg.modResults.contents = injectSigningConfig(cfg.modResults.contents, env);
    return cfg;
  });
};

module.exports = withReleaseSigning;
// Exported for the test: the string surgery is the part that silently breaks
// when the Expo template moves a line, and it must fail loudly rather than
// produce a gradle file that quietly signs with the debug key again.
module.exports.injectSigningConfig = injectSigningConfig;
